server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port:   587
    username: onlinebookingservice12@gmail.com
    password: uepmrgbyccrejiub
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: booking-service
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    generate-ddl: true
    properties:
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.PostgreSQL94Dialect
          format_sql: true
    show-sql: true


