server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: payment-service
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
    show-sql: true
